### ISSUE TITLE
Got the following error when trying to use Philips Adapter on Android

### ISSUE THREAD

**Issue by kevinhhbosch** [Bezirk-Bosch/AdapterZirks#11]
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by maass-bezirk** [comment]
The target and source compatibility lines need to be added to the upnpdiscovery module.
