### ISSUE TITLE
For Wunderound a space in city or state results in a space in the REST URL which breaks it

### ISSUE THREAD

**Issue by kevinhhbosch** [Bezirk-Bosch/AdapterZirks#13]
Need to replace space with underscore or "%20" for city and state names so that the URL is well formed.

**Comment by maass-bezirk** [comment]
This should just encode the entire thing with a URL encoder: https://docs.oracle.com/javase/7/docs/api/java/net/URLEncoder.html.

**Comment by maass-bezirk** [comment]
0910366eadcedd5c2310f4166aaf3235d239c23a
